INSERT INTO organizer (first_name, last_name) VALUES ('Justin', 'Reese');
INSERT INTO organizer (first_name, last_name) VALUES ('Colin', 'Dean');
INSERT INTO organizer (first_name, last_name) VALUES ('Erik', 'Swanson');
INSERT INTO organizer (first_name, last_name) VALUES ('Anna', 'Filippova');
INSERT INTO organizer (first_name, last_name) VALUES ('Matthew', 'Beatty');
INSERT INTO organizer (first_name, last_name) VALUES ('Jenny', 'Manning');
INSERT INTO organizer (first_name, last_name) VALUES ('Christopher', 'Luciano');
INSERT INTO organizer (first_name, last_name) VALUES ('Emma', 'Trimble');
INSERT INTO organizer (first_name, last_name) VALUES ('Jean', 'Lange');
